//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.UtentesAzure {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UtentesAzure.IUtentes")]
    public interface IUtentes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtentes/GetUtentes", ReplyAction="http://tempuri.org/IUtentes/GetUtentesResponse")]
        System.Data.DataSet GetUtentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtentes/GetUtentes", ReplyAction="http://tempuri.org/IUtentes/GetUtentesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtentes/GetUtentesByNIF", ReplyAction="http://tempuri.org/IUtentes/GetUtentesByNIFResponse")]
        System.Data.DataSet GetUtentesByNIF(int nif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtentes/GetUtentesByNIF", ReplyAction="http://tempuri.org/IUtentes/GetUtentesByNIFResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesByNIFAsync(int nif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtentes/GetUtentesByNome", ReplyAction="http://tempuri.org/IUtentes/GetUtentesByNomeResponse")]
        System.Data.DataSet GetUtentesByNome(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtentes/GetUtentesByNome", ReplyAction="http://tempuri.org/IUtentes/GetUtentesByNomeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesByNomeAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtentes/AddUtentes", ReplyAction="http://tempuri.org/IUtentes/AddUtentesResponse")]
        string AddUtentes(int idUtente, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtentes/AddUtentes", ReplyAction="http://tempuri.org/IUtentes/AddUtentesResponse")]
        System.Threading.Tasks.Task<string> AddUtentesAsync(int idUtente, string nome);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtentesChannel : Cliente.UtentesAzure.IUtentes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtentesClient : System.ServiceModel.ClientBase<Cliente.UtentesAzure.IUtentes>, Cliente.UtentesAzure.IUtentes {
        
        public UtentesClient() {
        }
        
        public UtentesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtentesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtentesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtentesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetUtentes() {
            return base.Channel.GetUtentes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesAsync() {
            return base.Channel.GetUtentesAsync();
        }
        
        public System.Data.DataSet GetUtentesByNIF(int nif) {
            return base.Channel.GetUtentesByNIF(nif);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesByNIFAsync(int nif) {
            return base.Channel.GetUtentesByNIFAsync(nif);
        }
        
        public System.Data.DataSet GetUtentesByNome(string nome) {
            return base.Channel.GetUtentesByNome(nome);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesByNomeAsync(string nome) {
            return base.Channel.GetUtentesByNomeAsync(nome);
        }
        
        public string AddUtentes(int idUtente, string nome) {
            return base.Channel.AddUtentes(idUtente, nome);
        }
        
        public System.Threading.Tasks.Task<string> AddUtentesAsync(int idUtente, string nome) {
            return base.Channel.AddUtentesAsync(idUtente, nome);
        }
    }
}
