//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.CasosAzure {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CasosAzure.ICasos")]
    public interface ICasos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetCasos", ReplyAction="http://tempuri.org/ICasos/GetCasosResponse")]
        System.Data.DataSet GetCasos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetCasos", ReplyAction="http://tempuri.org/ICasos/GetCasosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCasosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetCasosByNIF", ReplyAction="http://tempuri.org/ICasos/GetCasosByNIFResponse")]
        System.Data.DataSet GetCasosByNIF(int nif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetCasosByNIF", ReplyAction="http://tempuri.org/ICasos/GetCasosByNIFResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCasosByNIFAsync(int nif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetCasosByData", ReplyAction="http://tempuri.org/ICasos/GetCasosByDataResponse")]
        System.Data.DataSet GetCasosByData(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetCasosByData", ReplyAction="http://tempuri.org/ICasos/GetCasosByDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCasosByDataAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/AddCasos", ReplyAction="http://tempuri.org/ICasos/AddCasosResponse")]
        string AddCasos(string data, int idUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/AddCasos", ReplyAction="http://tempuri.org/ICasos/AddCasosResponse")]
        System.Threading.Tasks.Task<string> AddCasosAsync(string data, int idUtente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICasosChannel : Cliente.CasosAzure.ICasos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CasosClient : System.ServiceModel.ClientBase<Cliente.CasosAzure.ICasos>, Cliente.CasosAzure.ICasos {
        
        public CasosClient() {
        }
        
        public CasosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CasosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetCasos() {
            return base.Channel.GetCasos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCasosAsync() {
            return base.Channel.GetCasosAsync();
        }
        
        public System.Data.DataSet GetCasosByNIF(int nif) {
            return base.Channel.GetCasosByNIF(nif);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCasosByNIFAsync(int nif) {
            return base.Channel.GetCasosByNIFAsync(nif);
        }
        
        public System.Data.DataSet GetCasosByData(string data) {
            return base.Channel.GetCasosByData(data);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCasosByDataAsync(string data) {
            return base.Channel.GetCasosByDataAsync(data);
        }
        
        public string AddCasos(string data, int idUtente) {
            return base.Channel.AddCasos(data, idUtente);
        }
        
        public System.Threading.Tasks.Task<string> AddCasosAsync(string data, int idUtente) {
            return base.Channel.AddCasosAsync(data, idUtente);
        }
    }
}
