-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 09:42:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `mydb`.`material`
-- -----------------------------------------------------
CREATE TABLE material (
  idMaterial INT NOT NULL IDENTITY(1,1),
  nome VARCHAR(45) NULL,
  custo FLOAT NULL,
  PRIMARY KEY (idMaterial))


-- -----------------------------------------------------
-- Table `mydb`.`equipa`
-- -----------------------------------------------------
CREATE TABLE equipa (
  idEquipa INT NOT NULL IDENTITY(1,1),
  nome VARCHAR(45) NULL,
  PRIMARY KEY (idEquipa))


-- -----------------------------------------------------
-- Table `mydb`.`requisicao`
-- -----------------------------------------------------
CREATE TABLE requisicao (
  idRequisicao INT NOT NULL IDENTITY(1,1),
  entregue TINYINT NULL,
  idEquipa INT NOT NULL,
  PRIMARY KEY (idRequisicao),
  --INDEX fk_requisicao_equipa1_idx (equipa_idEquipa ASC) VISIBLE,
  CONSTRAINT fk_requisicao_equipa1
    FOREIGN KEY (idEquipa)
    REFERENCES equipa (idEquipa)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


-- -----------------------------------------------------
-- Table `mydb`.`utente`
-- -----------------------------------------------------
CREATE TABLE utente (
  idutente INT NOT NULL ,
  nome VARCHAR(45) NULL,
  PRIMARY KEY (idutente))


-- -----------------------------------------------------
-- Table `mydb`.`caso`
-- -----------------------------------------------------
CREATE TABLE caso (
  idcaso INT NOT NULL IDENTITY(1,1),
  data DATE NULL,
  idutente INT NOT NULL,
  PRIMARY KEY (idcaso),
  --INDEX fk_caso_utente1_idx (idutente ASC) VISIBLE,
  CONSTRAINT fk_caso_utente1
    FOREIGN KEY (idutente)
    REFERENCES utente (idutente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


-- -----------------------------------------------------
-- Table `mydb`.`contacto`
-- -----------------------------------------------------
CREATE TABLE contacto (
  idutente INT NOT NULL,
  idcaso INT NOT NULL,
  PRIMARY KEY (idutente, idcaso),
  --INDEX fk_utente_has_caso_caso1_idx (idcaso ASC) VISIBLE,
  --INDEX fk_utente_has_caso_utente1_idx (idutente ASC) VISIBLE,
  CONSTRAINT fk_utente_has_caso_utente1
    FOREIGN KEY (idutente)
    REFERENCES utente (idutente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_utente_has_caso_caso1
    FOREIGN KEY (idcaso)
    REFERENCES caso (idcaso)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  
  
-- -----------------------------------------------------
-- Table `mydb`.`fiscalizacao`
-- -----------------------------------------------------
CREATE TABLE fiscalizacao (
  idfiscalizacao INT NOT NULL IDENTITY(1,1),
  idcivil INT NOT NULL,
  nome VARCHAR(45) NULL,
  data DATE NULL,
  PRIMARY KEY (idfiscalizacao))  
  
  -- -----------------------------------------------------
-- Table `mydb`.`irregularidade`
-- -----------------------------------------------------
CREATE TABLE irregularidade (
  idirregularidade INT NOT NULL IDENTITY(1,1),
  descricao VARCHAR(45) NULL,
  idfiscalizacao INT NOT NULL,
  PRIMARY KEY (idirregularidade),
  CONSTRAINT fk_irregularidade_civil1
    FOREIGN KEY (idfiscalizacao)
    REFERENCES fiscalizacao (idfiscalizacao)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table `mydb`.`requisicaoMaterial`
-- -----------------------------------------------------
CREATE TABLE requisicaoMaterial (
  idRequisicaoMaterial INT NOT NULL IDENTITY(1,1),
  idMaterial INT NOT NULL,
  idRequisicao INT NOT NULL,
  qtd INT NULL,
  --INDEX fk_material_has_requisicao_requisicao1_idx (idRequisicao ASC) VISIBLE,
  --INDEX fk_material_has_requisicao_material1_idx (idMaterial ASC) VISIBLE,
  PRIMARY KEY (idRequisicaoMaterial),
  CONSTRAINT fk_material_has_requisicao_material1
    FOREIGN KEY (idMaterial)
    REFERENCES material (idMaterial)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_material_has_requisicao_requisicao1
    FOREIGN KEY (idRequisicao)
    REFERENCES requisicao (idRequisicao)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)


