//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.SOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAP.ICasos")]
    public interface ICasos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetCasos", ReplyAction="http://tempuri.org/ICasos/GetCasosResponse")]
        System.Data.DataSet GetCasos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetCasos", ReplyAction="http://tempuri.org/ICasos/GetCasosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCasosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/AddCasos", ReplyAction="http://tempuri.org/ICasos/AddCasosResponse")]
        System.Data.DataSet AddCasos(System.DateTime data, int idUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/AddCasos", ReplyAction="http://tempuri.org/ICasos/AddCasosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> AddCasosAsync(System.DateTime data, int idUtente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetUtentes", ReplyAction="http://tempuri.org/ICasos/GetUtentesResponse")]
        System.Data.DataSet GetUtentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetUtentes", ReplyAction="http://tempuri.org/ICasos/GetUtentesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetUtentesByNIF", ReplyAction="http://tempuri.org/ICasos/GetUtentesByNIFResponse")]
        System.Data.DataSet GetUtentesByNIF(int nif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetUtentesByNIF", ReplyAction="http://tempuri.org/ICasos/GetUtentesByNIFResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesByNIFAsync(int nif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetUtentesByNome", ReplyAction="http://tempuri.org/ICasos/GetUtentesByNomeResponse")]
        System.Data.DataSet GetUtentesByNome(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetUtentesByNome", ReplyAction="http://tempuri.org/ICasos/GetUtentesByNomeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesByNomeAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/AddUtentes", ReplyAction="http://tempuri.org/ICasos/AddUtentesResponse")]
        System.Data.DataSet AddUtentes(int idUtente, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/AddUtentes", ReplyAction="http://tempuri.org/ICasos/AddUtentesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> AddUtentesAsync(int idUtente, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetContacto", ReplyAction="http://tempuri.org/ICasos/GetContactoResponse")]
        System.Data.DataSet GetContacto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/GetContacto", ReplyAction="http://tempuri.org/ICasos/GetContactoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetContactoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/AddContacto", ReplyAction="http://tempuri.org/ICasos/AddContactoResponse")]
        System.Data.DataSet AddContacto(int idUtente, int idCaso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasos/AddContacto", ReplyAction="http://tempuri.org/ICasos/AddContactoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> AddContactoAsync(int idUtente, int idCaso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICasosChannel : Cliente.SOAP.ICasos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CasosClient : System.ServiceModel.ClientBase<Cliente.SOAP.ICasos>, Cliente.SOAP.ICasos {
        
        public CasosClient() {
        }
        
        public CasosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CasosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetCasos() {
            return base.Channel.GetCasos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCasosAsync() {
            return base.Channel.GetCasosAsync();
        }
        
        public System.Data.DataSet AddCasos(System.DateTime data, int idUtente) {
            return base.Channel.AddCasos(data, idUtente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AddCasosAsync(System.DateTime data, int idUtente) {
            return base.Channel.AddCasosAsync(data, idUtente);
        }
        
        public System.Data.DataSet GetUtentes() {
            return base.Channel.GetUtentes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesAsync() {
            return base.Channel.GetUtentesAsync();
        }
        
        public System.Data.DataSet GetUtentesByNIF(int nif) {
            return base.Channel.GetUtentesByNIF(nif);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesByNIFAsync(int nif) {
            return base.Channel.GetUtentesByNIFAsync(nif);
        }
        
        public System.Data.DataSet GetUtentesByNome(string nome) {
            return base.Channel.GetUtentesByNome(nome);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUtentesByNomeAsync(string nome) {
            return base.Channel.GetUtentesByNomeAsync(nome);
        }
        
        public System.Data.DataSet AddUtentes(int idUtente, string nome) {
            return base.Channel.AddUtentes(idUtente, nome);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AddUtentesAsync(int idUtente, string nome) {
            return base.Channel.AddUtentesAsync(idUtente, nome);
        }
        
        public System.Data.DataSet GetContacto() {
            return base.Channel.GetContacto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetContactoAsync() {
            return base.Channel.GetContactoAsync();
        }
        
        public System.Data.DataSet AddContacto(int idUtente, int idCaso) {
            return base.Channel.AddContacto(idUtente, idCaso);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AddContactoAsync(int idUtente, int idCaso) {
            return base.Channel.AddContactoAsync(idUtente, idCaso);
        }
    }
}
